print("Selamat Datang")

nama = input("masukan nama: ")
kelas = input("kelas: ")
prodi = input("prodi: ")
kampus = input("kampus: ")
umur = int(input("umur: "))
tinggibadan = float(input("tinggi_badan:"))

print("nama saya: ", nama)
print("kelas: ", kelas)
print("prodi: ", prodi)
print("hello {} selamat datang di kampus {}".format(nama, kampus))
print("nama saya %s, umur saya %d, tinggi saya %f" %(nama, umur, tinggibadan))

# # a = int(input("masukkan a: "))
# # b = int(input("masukkan b: "))
# # # print(a, 'x7', b, '=', a*b)
# # # print("{} * {} = {}".format(a, b, a*b))
# # # print("{1} - {0} * {2} = {3}".format(8, 2, 2, 2-8*2))
# # # print("{a} + {b} = {c}".format(a=a, b=b, c=a+b))
# # print(f"{a} + {b} = {a+b}")
# # print(f"{a} - {b} = {a-b}")
# # print(f"{a} * {b} = {a*b}")
# # print(f"{a} / {b} = {a/b}")
# # print(f"{a} % {b} = {a%b}")
# # print(f"{a} pangkat {b} = {a**b}")
# #
# # print(f"{a} == {b} = {a==b}")
# # print(f"{a} != {b} = {a!=b}")
# # print(f"{a} > {b} = {a>b}")
# # print(f"{a} >= {b} = {a>=b}")
# # print(f"{a} < {b} = {a<b}")
# # print(f"{a} <= {b} = {a<=b}")
#
# print(4 << 5)
# print(4 >> 5)